### ISSUE TITLE
when do i exit sudo because i got warning about using pip as root user

### ISSUE THREAD

**Issue by Awildernessboy** [bclittleua/SEA-BE-22#2]

**Comment by Awildernessboy** [comment]
i got it when i install discord to debian

**Comment by bclittleua** [comment]
you can switch from the root user after you've installed the packages. the reason i have you install these packages as root is because if done as a normal user it doesn't install them properly and the pathing gets confusing. you can switch out of `sudo -i` with `su admin`. good luck!
